import {
  IconActivity,
  IconAirBalloon,
  IconAlarm,
  IconAlertTriangle,
  IconAnchor,
  IconArchive,
  IconArmchair,
  IconAtom,
  IconAward,
  IconBackpack,
  IconBattery,
  IconBell,
  IconBike,
  IconBook,
  IconBriefcase,
  IconBulb,
  IconCake,
  IconCalculator,
  IconCalendar,
  IconCamera,
  IconCar,
  IconCash,
  IconChartBar,
  IconCloud,
  IconCoffee,
  IconCompass,
  IconCreditCard,
  IconDeviceGamepad,
  IconDroplet,
  IconEye,
} from '@tabler/icons-react-native'

export const tablerIcons = [
  { name: 'IconActivity', component: IconActivity },
  { name: 'IconAirBalloon', component: IconAirBalloon },
  { name: 'IconAlarm', component: IconAlarm },
  { name: 'IconAlertTriangle', component: IconAlertTriangle },
  { name: 'IconAnchor', component: IconAnchor },
  { name: 'IconArchive', component: IconArchive },
  { name: 'IconArmchair', component: IconArmchair },
  { name: 'IconAtom', component: IconAtom },
  { name: 'IconAward', component: IconAward },
  { name: 'IconBackpack', component: IconBackpack },
  { name: 'IconBattery', component: IconBattery },
  { name: 'IconBell', component: IconBell },
  { name: 'IconBike', component: IconBike },
  { name: 'IconBook', component: IconBook },
  { name: 'IconBriefcase', component: IconBriefcase },
  { name: 'IconBulb', component: IconBulb },
  { name: 'IconCake', component: IconCake },
  { name: 'IconCalculator', component: IconCalculator },
  { name: 'IconCalendar', component: IconCalendar },
  { name: 'IconCamera', component: IconCamera },
  { name: 'IconCar', component: IconCar },
  { name: 'IconCash', component: IconCash },
  { name: 'IconChartBar', component: IconChartBar },
  { name: 'IconCloud', component: IconCloud },
  { name: 'IconCoffee', component: IconCoffee },
  { name: 'IconCompass', component: IconCompass },
  { name: 'IconCreditCard', component: IconCreditCard },
  { name: 'IconDeviceGamepad', component: IconDeviceGamepad },
  { name: 'IconDroplet', component: IconDroplet },
  { name: 'IconEye', component: IconEye },
]
