import {
  IconActivity,
  IconAirBalloon,
  IconAlarm,
  IconAlertTriangle,
  IconAnchor,
  IconArchive,
  IconArmchair,
  IconAtom,
  IconAward,
  IconBackpack,
  IconBarbell,
  IconBattery,
  IconBed,
  IconBell,
  IconBike,
  IconBook,
  IconBrain,
  IconBriefcase,
  IconBulb,
  IconCake,
  IconCalculator,
  IconCalendar,
  IconCamera,
  IconCar,
  IconCash,
  IconChartAreaLine,
  IconChartBar,
  IconCloud,
  IconCoffee,
  IconCompass,
  IconCreditCard,
  IconDeviceGamepad,
  IconDroplet,
  IconEye,
  IconMovie,
  IconMusic,
  IconPhoto,
  IconProps,
  IconSalad,
  IconShoppingBag,
  IconToolsKitchen2,
} from '@tabler/icons-react-native'

export const categoriesIcons: Record<string, React.ComponentType<IconProps>> = {
  'icon-default-category': IconPhoto,
  'icon-tools-kitchen': IconToolsKitchen2,
  'icon-shopping-bag': IconShoppingBag,
  'icon-bed': IconBed,
  'icon-movie': IconMovie,
  'icon-coffee': IconCoffee,
  'icon-barbell': IconBarbell,
  'icon-brain': IconBrain,
  'icon-chart-area-line': IconChartAreaLine,
  'icon-music': IconMusic,
  'icon-salad': IconSalad,
  'icon-activity': IconActivity,
  'icon-air-balloon': IconAirBalloon,
  'icon-alarm': IconAlarm,
  'icon-alert-triangle': IconAlertTriangle,
  'icon-anchor': IconAnchor,
  'icon-archive': IconArchive,
  'icon-armchair': IconArmchair,
  'icon-atom': IconAtom,
  'icon-award': IconAward,
  'icon-backpack': IconBackpack,
  'icon-battery': IconBattery,
  'icon-bell': IconBell,
  'icon-bike': IconBike,
  'icon-book': IconBook,
  'icon-briefcase': IconBriefcase,
  'icon-bulb': IconBulb,
  'icon-cake': IconCake,
  'icon-calculator': IconCalculator,
  'icon-calendar': IconCalendar,
  'icon-camera': IconCamera,
  'icon-car': IconCar,
  'icon-cash': IconCash,
  'icon-chart-bar': IconChartBar,
  'icon-cloud': IconCloud,
  'icon-compass': IconCompass,
  'icon-credit-card': IconCreditCard,
  'icon-device-gamepad': IconDeviceGamepad,
  'icon-droplet': IconDroplet,
  'icon-eye': IconEye,
}
